apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: order-service
        scrape_interval: 15s
        static_configs:
          - targets:
              - order-service.order-service.svc.cluster.local:8000
        metrics_path: /metrics
        authorization:
          type: Bearer
          credentials_file: /etc/prometheus/secrets/metrics-token
