apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: order-service
type: Opaque
stringData:
  POSTGRES_USER: orders
  POSTGRES_PASSWORD: "__DB_PASSWORD__"
  POSTGRES_DB: orders
  API_KEY: "__API_KEY__"
