name: CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: orderservice-projectdevops
  IMAGE: ghcr.io/${{ github.repository_owner }}/orderservice-projectdevops

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ github.sha }}
            ${{ env.IMAGE }}:latest

      - name: Copy manifests to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "k8s/"
          target: "~/order-service"

      - name: Replace placeholders and deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: IMAGE,IMAGE_NAME
          script: |
            cd ~/order-service/k8s
            sed -i 's|__GITHUB_USER__|${{ github.repository_owner }}|g' deployment.yaml
            sed -i 's|__IMAGE_NAME__|${{ env.IMAGE_NAME }}|g' deployment.yaml
            sed -i 's|__DB_PASSWORD__|${{ secrets.DB_PASSWORD }}|g' postgres-secret.yaml
            kubectl apply -f namespace.yaml
            kubectl apply -f postgres-secret.yaml
            kubectl apply -f postgres-pvc.yaml
            kubectl apply -f postgres-deployment.yaml
            kubectl apply -f postgres-service.yaml
            kubectl apply -f service.yaml
            kubectl rollout status deployment/postgres \
              -n order-service --timeout=120s
            kubectl apply -f deployment.yaml
            kubectl set image deployment/order-service \
              order-service=${IMAGE}:${{ github.sha }} \
              -n order-service
            kubectl rollout status deployment/order-service \
              -n order-service --timeout=120s
